# title: Jihyun Mun
# description: A minimal and beautiful Jekyll theme best for writing and note-taking.
skin: daylight

author: Jihyun Mun
avatar: /assets/images/portrait.jpg
email: jhhh_1202@snu.ac.kr

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# disqus:

# Jekyll
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# SEO and Social
logo: logo.png
social:
  name: Jihyun Mun
  links:
    - https://www.linkedin.com/in/jihyun-mun-b65a58142/
    - https://github.com/jihyunmun?tab=repositories

google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
